#!/bin/bash

export REACT_APP_TITLE="Onderzoeksbibliotheek Provincie Overijssel" 
export REACT_APP_TYPE_APP="ob" 
export REACT_APP_HOME_HTML="<h1><strong>Welkom bij de Onderzoeksbibliotheek Overijssel</strong></h1><p>De provincie Overijssel laat onderzoek doen op allerlei gebieden waar Overijssel bij betrokken is. Dat kan gaan over het (provinciale) beleid, de uitvoering ervan of een evaluatie. Doel van de onderzoeken is het vergroten van de effectiviteit en/of efficiency bij projecten waar de provincie bij betrokken is. Daarbij gaat het meestal over het effect van beleid, de behaalde doelstellingen of het proces hoe daar gekomen is.</p><p>De onderzoeken bevatten veel informatie die vaak ook voor derden van belang is. Om deze kennis te delen, publiceert de provincie een openbaar doorzoekbaar register met onderzoeken: de Onderzoeksbibliotheek Overijssel.</p><p>Ben je op zoek naar een specifiek onderzoek? Wil je weten of er op een bepaald terrein al eens onderzoek is gedaan? Dan ben je hier aan het juiste adres.</p>" 
export REACT_APP_CONTACT_HTML="<h1>Contactgegevens</h1><p>De informatie in de Onderzoeksbibliotheek wordt beschikbaar gesteld door het team Beleidsinformatie van de provincie Overijssel.</p><p>Heb je vragen, suggesties of tips, aarzel dan niet contact op te nemen.</p><p>Stuur je email naar: <a href="mailto:kennishub@overijssel.nl">kennishub@overijssel.nl</a></p></br><p>Provincie Overijssel wil dat iedereen haar online diensten gemakkelijk kan gebruiken. Daarom werken we aan het verbeteren van de digitale toegankelijkheid van onze websites. In het Besluit digitale toegankelijkheid overheid staat dat websites van overheden moeten voldoen aan de standaard EN 301 549. In deze standaard staan de eisen van WCAG 2.1, niveau A en AA. Overheden moeten daarover verantwoording afleggen in een gepubliceerde toegankelijkheidsverklaring.</p><p><a href="https://www.toegankelijkheidsverklaring.nl/register/27375">Volg de link voor de volledige toegankelijkheidsverklaring</a></p><p><a href="https://dashboard.digitoegankelijk.nl/organisaties/4">Bekijk het overzicht van alle toegankelijkheidsverklaringen van provincie Overijssel</a></p><p>Heeft u vragen of opmerkingen? Of loopt u tegen problemen aan als het gaat over digitale toegankelijkheid? Neem contact op met <a href="mailto:digitoegankelijk@overijssel.nl">digitoegankelijk@overijssel.nl</a>.</p>" 
export REACT_APP_API_HOST="http://admin.geoportaal.local" 
export REACT_APP_PUBLIC_PORTAL_HOST="http://www.geoportaal.local" 
export REACT_APP_DEPLOYMENT_ACCEPTANCE="false" 
export REACT_APP_DISPLAY_STATS_ANALYTICS="false" 
npm start
