#!/bin/bash

export REACT_APP_TITLE="Onderzoeksbibliotheek Provincie Overijssel"
export REACT_APP_TYPE_APP="ob"
export REACT_APP_HOME_HTML="<h1><strong>Welkom bij de Onderzoeksbibliotheek Overijssel</strong></h1><p>Welkom bij de onderzoeksbibliotheek van de provincie Overijssel! Binnenkort kunt U deze pagina gebruiken voor het opzoeken van onderzoeksrapporten die door of in opdracht van de provincie Overijssel zijn opgesteld. De komende maanden zijn we bezig met het vullen van de bibliotheek. Rapporten zoeken en vinden kan bij het tabblad <a href="/list">documenten</a>. Bij het tabblad <a href="/contact">contact</a> staan de contactgegevens.</p>"
export REACT_APP_CONTACT_HTML="<h1>Contactgegevens</h1><p>De informatie in de Onderzoeksbibliotheek wordt beschikbaar gesteld door het team Beleidsinformatie van de provincie Overijssel.</p><p>Heb je vragen, suggesties of tips, aarzel dan niet contact op te nemen.</p><p>Stuur je email naar: <a href="mailto:kennishub@overijssel.nl">kennishub@overijssel.nl</a></p></br><p>Provincie Overijssel wil dat iedereen haar online diensten gemakkelijk kan gebruiken. Daarom werken we aan het verbeteren van de digitale toegankelijkheid van onze websites. In het Besluit digitale toegankelijkheid overheid staat dat websites van overheden moeten voldoen aan de standaard EN 301 549. In deze standaard staan de eisen van WCAG 2.1, niveau A en AA. Overheden moeten daarover verantwoording afleggen in een gepubliceerde toegankelijkheidsverklaring.</p><p><a href="https://www.toegankelijkheidsverklaring.nl/register/27375">Volg de link voor de volledige toegankelijkheidsverklaring</a></p><p><a href="https://dashboard.digitoegankelijk.nl/organisaties/4">Bekijk het overzicht van alle toegankelijkheidsverklaringen van provincie Overijssel</a></p><p>Heeft u vragen of opmerkingen? Of loopt u tegen problemen aan als het gaat over digitale toegankelijkheid? Neem contact op met <a href="mailto:digitoegankelijk@overijssel.nl">digitoegankelijk@overijssel.nl</a>.</p>"
export REACT_APP_API_HOST="http://admin.geoportaal.local"
export REACT_APP_PUBLIC_PORTAL_HOST="http://www.geoportaal.local"
export REACT_APP_DEPLOYMENT_ACCEPTANCE="false"
export REACT_APP_DISPLAY_STATS_ANALYTICS="false"
npm start
